# Generated by Django 3.0.6 on 2020-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likesum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
